image: python:3.9

stages:
  - build
  # - test
  - cache

cache:
  key: 'SingleCacheKey'
  paths:
    - .cache/pip
    - venv/
  policy: pull

before_script:
  - cd API
  - apt-get update && apt-get install -y libpq-dev
  - source venv/bin/activate
  - pip install --upgrade pip

build api:
  stage: build
  except:
    - schedules
  script:   
    - source venv/bin/activate
    - pip install -r requirements.txt
    - uvicorn main:app --host 0.0.0.0  --port 8000 --reload &
    - sleep 5
  cache:
    policy: pull-push
  
cache update:
  stage: cache
  script:
    - source venv/bin/activate
    - pip install -r requirements.txt
  cache:
    policy: push
  only:
    - schedules


# test api:
# test artifact:
#   image: alpine
#   stage: test
#   except:
#     - schedules
#   cache:
#     paths: []
#   script:
#     - grep -q "Gatsby" ./public/index.html

# test website:
#   stage: test
#   except:
#     - schedules
#   script:
#     - npm install
#     - npm install -g gatsby-cli
#     - gatsby serve &
#     - sleep 3
#     - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"
