image: luizcunhaoliveira/python_0:latest

stages:
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
    - venv/
    - API/
    - Tests/


before_script:
  - python -m venv venv
  - source venv/bin/activate


build api:
  stage: build
  except:
    - schedules
  script:   
    - cd API
    - uvicorn main:app --host 0.0.0.0  --port 8000 --reload &
    - sleep 5
  artifacts:
    expire_in: 1 hour
    paths:
      - API/
  
test llm:
  stage: test
  except:
    - schedules
  script:
    - cd Tests
    - pytest -vv
  artifacts:
    when: always
    expire_in: 1 hour
    paths:
      - tests_reports/
    reports:
      junit: tests_reports/junit.xml

