# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
    volumes:
      - .:/app
    ports:
      - 8000:5000
  
  db:
    hostname: db
    image: ankane/pgvector
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
#Run the following commands (local)  
#docker-compose build
#docker-compose up -d
#browser: http://127.0.0.1:8000/
