name: Push to GitLab

on:
  push:
    branches:
      - main  # This ensures the workflow runs only for pushes to the main branch

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GENAIAPITOKEN }}
      run: |
        # Configure Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "luizdavid.93@hotmail.com"
        
        # Add GitLab remote
        git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.com/LuizDavidOlv/GenerativeAiAPI.git"
        
        # Push to GitLab
        git fetch --unshallow --no-tags
        git push gitlab main
